export interface Orcamento {
    id?: number,
    nome?: string | null,
    razaoSocial?: string | null,
    nomeFantasia?: string | null,
    email?: string | null,
    telefone?: string | null,
    cidade?: string | null,
    uf?: string | null,
    data?: string | null,
    alturaDaParede: number,
    larguraDaParede: number,
    alturaDosModulos: number,
    larguraDosModulos: number,
    areaModulos: number,
    totalDeModulosInteiros: number,
    totalDeModulosCantoneira: number | null,
    totalDeModulosNicho: number | null,
    totalDeModulosDuplos: number,
    totalDeTopos: number, 
    totalDeToposNicho: number,
    totalDeToposDuplos: number,
    totalDePlacasHorizontais: number,
    totalDePlacasVerticais: number,
    totalDeVasos: number,
    totalDeBolsasDeSubstrato: number,
    totalDeIniciaisFinais: number,
    totalDePinosDeTravamento: number,
    totalDePlacasNicho: number, 
    totalDePlacasDuplo: number,
    totalDePlantas: number,
    totalDeGotejadores: number,
    totalTuboCego: number,
    totalCotovelos: number,
    totalTes: number,
    totalFinalDeLinha: number,
    totalConectorInicial: number,
    totalParafusos: number,
    totalBuchas: number,
    totalDePlacasCantoneiras: number,
    totalDePlacasVerticaisCantoneira: number,
    totalDeUniaoCantoneira: number,
    totalDeVasosCantoneira: number,
    totalDeBolsaDeSubstratoCantoneira: number,
    precoTotalEstrutura: number,
    precoTotalIrrigacao: number,
    precoTotalFixacao: number,
    precoTotal: number,
    
}